name: Bug Report
description: Use this template to report a bug you have encountered.

assignees: []
labels: bug
title: "[BUG] - Short description of the issue"

body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to report a bug! Please fill out the details below to help us understand and address the issue.

- type: input
  id: bug_description
  attributes:
    label: Bug Description
    description: A clear and concise description of what the bug is.
    placeholder: "Describe the bug here..."
  validations:
    required: true

- type: textarea
  id: how_to_recreate
  attributes:
    label: How to Recreate
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Step 1
      2. Step 2
      3. Step 3
  validations:
    required: true

- type: textarea
  id: expected_behavior
  attributes:
    label: Expected Behavior
    description: What you expected to happen.
    placeholder: "Describe what you expected to happen..."
  validations:
    required: true

- type: input
  id: screenshots
  attributes:
    label: Screenshots (if applicable)
    description: Add screenshots to help explain your problem.
    placeholder: "Provide links to screenshots if you have any..."

- type: textarea
  id: additional_context
  attributes:
    label: Additional Context
    description: Any other context about the problem, such as environment or configuration.
    placeholder: "Provide any additional information here..."
